#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: distutils3
#
Name     : pypi-patatt
Version  : 0.6.3
Release  : 1
URL      : https://files.pythonhosted.org/packages/fa/62/8adfadbc130cd33696e06c9c2f3ea36252c2e3dd1387cfdea0bc3aa10172/patatt-0.6.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/fa/62/8adfadbc130cd33696e06c9c2f3ea36252c2e3dd1387cfdea0bc3aa10172/patatt-0.6.3.tar.gz
Summary  : A simple library to add cryptographic attestation to patches sent via email
Group    : Development/Tools
License  : MIT
Requires: pypi-patatt-bin = %{version}-%{release}
Requires: pypi-patatt-license = %{version}-%{release}
Requires: pypi-patatt-man = %{version}-%{release}
Requires: pypi-patatt-python = %{version}-%{release}
Requires: pypi-patatt-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(pynacl)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
patatt: cryptographic patch attestation for the masses
======================================================

%package bin
Summary: bin components for the pypi-patatt package.
Group: Binaries
Requires: pypi-patatt-license = %{version}-%{release}

%description bin
bin components for the pypi-patatt package.


%package license
Summary: license components for the pypi-patatt package.
Group: Default

%description license
license components for the pypi-patatt package.


%package man
Summary: man components for the pypi-patatt package.
Group: Default

%description man
man components for the pypi-patatt package.


%package python
Summary: python components for the pypi-patatt package.
Group: Default
Requires: pypi-patatt-python3 = %{version}-%{release}

%description python
python components for the pypi-patatt package.


%package python3
Summary: python3 components for the pypi-patatt package.
Group: Default
Requires: python3-core
Provides: pypi(patatt)
Requires: pypi(pynacl)

%description python3
python3 components for the pypi-patatt package.


%prep
%setup -q -n patatt-0.6.3
cd %{_builddir}/patatt-0.6.3
pushd ..
cp -a patatt-0.6.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1684517963
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-patatt
cp %{_builddir}/patatt-%{version}/COPYING %{buildroot}/usr/share/package-licenses/pypi-patatt/1f46e4a586f3c086bc2478b423d4cb96ab6748e4 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/patatt

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-patatt/1f46e4a586f3c086bc2478b423d4cb96ab6748e4

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/patatt.5

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
